---

- name: copy prometheus main config
  template:
    src: "etc/prometheus/prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    validate: "{{ prometheus_bin_dir }}/promtool check-config %s"
  notify:
    - reload prometheus

- name: "copy rule files from playbook's directory"
  copy:
    src: "{{ playbook_dir }}/files/rules/{{ item }}"
    dest: "{{ prometheus_rule_path }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    validate: "{{ prometheus_bin_dir }}/promtool check-rules %s"
  with_items:
    - "{{ prometheus_rule_files }}"
  notify:
    - reload prometheus

- name: "copy target group files from playbook's directory"
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_file_sd_config_dir }}/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
  with_fileglob:
    - "{{ playbook_dir }}/files/tgroups/*"
  notify:
    - reload prometheus
