---

- name: copy rule files from playbook directory
  copy:
    src: "{{ playbook_dir }}/files/rules/{{ item }}"
    dest: "{{ prometheus_rules_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    validate: "{{ prometheus_bin_dir }}/promtool check-rules %s"
  with_items:
    - "{{ prometheus_rules_files }}"
  notify:
    - reload prometheus

- name: copy prometheus 1st part config
  template:
    src: "etc/prometheus/prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/conf.d/1-prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644

- name: copy another config parts
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/conf.d/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
  with_fileglob:
    - "{{ playbook_dir }}/files/config_parts/*"

- name: create main config from parts
  assemble:
    src: "{{ prometheus_config_dir }}/conf.d"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    remote_src: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    delimiter: '\n### START FRAGMENT ###'
    validate: "{{ prometheus_bin_dir }}/promtool check-config %s"
  notify:
    - reload prometheus

- name: copy target group files from playbook directory
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_file_sd_config_dir }}/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
  with_fileglob:
    - "{{ playbook_dir }}/files/tgroups/*"
